version: "3"
services:
  web:
    build: .
    volumes:
      - .:/app
    deploy:
      replicas: 2
    ports:
      - 8000:8000
    environment:
      DEBUG: "True"
      PYTHONUNBUFFERED: "1"
      CASSANDRA_HOST: '["db"]'
  db:
    image: cassandra:latest
    ports:
      - 9042:9042
    environment:
      CASSANDRA_START_RPC: "true"
